<a href="https://colab.research.google.com/github/youssadi99/deeplearning/blob/main/d%C3%A9mo_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Tue May 13 14:00:35 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Tensor in torch

In [ ]:
#scalaire
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(7)
0
torch.Size([])


In [ ]:
#vecteur
vector = torch.tensor([2,3,5])
print(vector)
print(vector.ndim) #== number of []
print(vector.shape)

tensor([2, 3, 5])
1
torch.Size([3])


In [ ]:
#matrice
MATRIX = torch.tensor([[2,3,5],
                       [1,7,4]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

tensor([[2, 3, 5],
        [1, 7, 4]])
2
torch.Size([2, 3])
tensor([1, 7, 4])


In [ ]:
#tenseur multi dimension
TENSOR = torch.tensor([
    [[2,3,5],[1,7,4]],
    [[8,8,8],[7,7,7]],
    [[1,1,1],[4,4,4]],
    [[0,0,0],[9,9,9]]
    ])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[1])

tensor([[[2, 3, 5],
         [1, 7, 4]],

        [[8, 8, 8],
         [7, 7, 7]],

        [[1, 1, 1],
         [4, 4, 4]],

        [[0, 0, 0],
         [9, 9, 9]]])
3
torch.Size([4, 2, 3])
tensor([[8, 8, 8],
        [7, 7, 7]])


## Random tensors

In [ ]:
#tenseur avec des valeurs aléatoires
RANDOM_TENSOR = torch.rand(3,4)
print(RANDOM_TENSOR)
#tensor with same image size
RANDOM_IMAGE_TENSOR = torch.rand(3,224,224)
print(RANDOM_IMAGE_TENSOR.shape)

tensor([[0.5755, 0.2897, 0.0367, 0.2609],
        [0.2212, 0.6317, 0.9249, 0.1807],
        [0.1413, 0.7143, 0.2506, 0.9664]])
torch.Size([3, 224, 224])


In [ ]:
ZERO_TENSOR = torch.zeros(3,4)
print(ZERO_TENSOR)

In [ ]:
ONES_TENSOR = torch.ones(3,4)
print(ONES_TENSOR)
print(ONES_TENSOR.dtype)

In [ ]:
TORCH_RANGE = torch.arange(1,11)
print(TORCH_RANGE)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
T1 = torch.arange(start=0,end=10,step=2)
print(T1)
T0 = torch.zeros_like(input=T1)
print(T0)

tensor([0, 2, 4, 6, 8])
tensor([0, 0, 0, 0, 0])


In [ ]:
#dtype by default is float32 = meaning that each floating number is represented by 32bit (high quality expression vs float16 for example)
#device = cpu or cuda
#requires_grad = whether to track or not gradients with this tensors operation
float32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
print(float32_tensor)

tensor([3., 6., 9.])


In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor)

In [ ]:
#Tensor Attribute
print(f"tensor dtype: {float32_tensor.dtype}")
print(f"tensor device: {float32_tensor.device}")
print(f"tensor shape: {float32_tensor.shape}")

In [ ]:
#tensor operations
some_tensor = torch.tensor([1,2,3])
print(some_tensor)

In [ ]:
some_tensor + 10

In [ ]:
torch.add(some_tensor,10)

In [ ]:
some_tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.multiply(some_tensor,10)

In [ ]:
t1 = torch.rand(2,3)
t2 = torch.rand(3,2)
print(t1 * t1) #element wise multiplication
print(torch.matmul(t1,t2)) #matrix multiplication (we can write it also as torch.mm(t1,t2))

In [ ]:
torch.mm(t1, t1.T)

In [ ]:
x = torch.arange(1,10)
print(x)

In [ ]:
torch.max(x), torch.min(x), x.min(), x.max()
#

In [ ]:
#x.mean()
x.dtype

In [ ]:
x.type(torch.float32).mean()


In [ ]:
x.sum()

In [ ]:
x.argmin(), x.argmax()

## Reshaping, View, Stacking, squeezing and unsequeezing

In [ ]:
#reshape
x = torch.arange(1.,10.)
print(x, x.shape)
x_reshaped = x.reshape(1,9) #adding an extra one dimension
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [ ]:
x_reshaped = x.reshape(9,1)
print(x_reshaped)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [ ]:
print(x_reshaped.ndim)

In [ ]:
# les view (changing z is changing x; they both share the memory)
z = x.view(1,9) #like shape
print(z)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [ ]:
z[:, 0] = 5
print(z)
print(x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
#torch stacks
stacked = torch.stack([x,x,x,x], dim=0)
stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(stacked.shape, x.shape)

In [ ]:
stacked2 = torch.stack([x,x,x,x], dim=1)
stacked2

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
print(stacked2.shape)

In [ ]:
#squeeze : remove all 1 dimensions from a target tensor
y = torch.rand(1,2,1,10)
print(y)
print(y.shape)
y_squeezed = y.squeeze()
print(y_squeezed)
print(y_squeezed.shape)

tensor([[[[0.4349, 0.5281, 0.1719, 0.3152, 0.5994, 0.4029, 0.4599, 0.9127,
           0.7934, 0.5214]],

         [[0.3992, 0.9273, 0.5007, 0.6444, 0.5309, 0.1294, 0.8642, 0.2301,
           0.2956, 0.6642]]]])
torch.Size([1, 2, 1, 10])
tensor([[0.4349, 0.5281, 0.1719, 0.3152, 0.5994, 0.4029, 0.4599, 0.9127, 0.7934,
         0.5214],
        [0.3992, 0.9273, 0.5007, 0.6444, 0.5309, 0.1294, 0.8642, 0.2301, 0.2956,
         0.6642]])
torch.Size([2, 10])


In [ ]:
#unsquuze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(y_unsqueezed)
print(y_unsqueezed.shape)

tensor([[[0.4349, 0.5281, 0.1719, 0.3152, 0.5994, 0.4029, 0.4599, 0.9127,
          0.7934, 0.5214],
         [0.3992, 0.9273, 0.5007, 0.6444, 0.5309, 0.1294, 0.8642, 0.2301,
          0.2956, 0.6642]]])
torch.Size([1, 2, 10])


In [ ]:
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
print(y_squeezed.shape)
print(y_unsqueezed.shape)

torch.Size([2, 10])
torch.Size([2, 1, 10])


In [ ]:
#permute
x = torch.randn(2,3,4)
print(x)
print(x.shape)
q = x.permute(2,0,1)
print(q.shape)

tensor([[[ 0.8977,  0.1144, -2.0771,  0.4874],
         [ 1.3430, -0.1658,  1.9475, -0.1504],
         [ 0.3288, -2.1620, -0.9904,  1.8373]],

        [[ 1.6008, -2.5697, -0.4778, -0.1045],
         [ 0.6639,  0.3099,  1.8616,  0.8885],
         [-0.1742,  0.3731,  2.2530,  2.4084]]])
torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [ ]:
print(x.permute(2,0,1).shape)

In [ ]:
image = torch.rand(224,224,3)
print(image.shape)
image_permuted = image.permute(2,0,1)
print(image_permuted.shape)

#Slicing and convesrion to numpy


In [ ]:
#indexing
x = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
print(x.shape)
print(x)
print(x[0])
print(x[0][1])
print(x[0,1])
print(x[0][1][2])
print(x[0, 1, 2])
print(x[0, :, 2])
print(x[0, 1, :])
print(x[0, :, :])
print(x[:, 1, :])
print(x[:, :, 2])
print(x[:, :, :])

torch.Size([2, 3, 4])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([4., 5., 6., 7.])
tensor([4., 5., 6., 7.])
tensor(6.)
tensor(6.)
tensor([ 2.,  6., 10.])
tensor([4., 5., 6., 7.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 4.,  5.,  6.,  7.],
        [16., 17., 18., 19.]])
tensor([[ 2.,  6., 10.],
        [14., 18., 22.]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])


In [ ]:
#nympy to tensor and vice versa
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array)
print(tensor)
print(tensor.numpy())

In [ ]:
#random seed
torch.manual_seed(42)
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
#transer tensor to GPU
tensor_on_gpu = random_tensor.to(device)
print(tensor_on_gpu)

In [ ]:
#on peut pas convertir un tensor qui tourne en gpu en un tableau numpy il faut changer de device en cpu
tensor_on_gpu = random_tensor.cpu().numpy()
print(tensor_on_gpu)

# Tensor and NN layers

In [ ]:
import torch.nn as nn

m = nn.Linear(20, 30)
print(m)
input = torch.randn(2, 20)
print(input)
output = m(input)
print(output)
output.shape

Linear(in_features=20, out_features=30, bias=True)
tensor([[ 1.1483,  0.9896,  0.1185,  0.9838, -2.4790,  1.0514,  0.7052, -0.4767,
          0.9602, -1.0891, -1.2615, -2.0549,  0.6103,  1.0775, -0.8897,  2.3869,
          0.5349,  0.2829,  0.2560, -1.0973],
        [ 0.8444,  1.2230, -0.6072, -1.8007, -0.5021,  0.5068,  0.2829, -1.1814,
         -0.9002,  2.1022,  0.1331,  0.0224,  0.6478, -0.6848, -0.7950, -1.7334,
          1.1859,  0.4466,  1.1301, -0.3334]])
tensor([[-0.4312, -0.4252,  0.6011,  0.3211,  0.6751,  0.6377,  0.8863, -0.6096,
         -0.4966, -0.2253,  0.3574, -0.0236,  0.2998, -1.4840,  0.0460, -1.2943,
          0.0879,  0.5404, -1.0395,  0.6145, -0.3112,  0.6164, -1.7344, -0.8575,
          0.3700,  0.7115,  0.1948, -0.2313,  1.5597, -0.5146],
        [ 0.3925, -0.5947,  0.0277, -0.2948,  0.6366,  0.0986,  0.0822,  0.9156,
          0.3705,  0.2394, -0.9778,  1.3816, -0.5492,  0.9645,  0.8177,  0.4922,
         -0.2503,  1.3449,  0.1672, -0.6056,  0.3460, -0.3559, 

torch.Size([2, 30])

In [ ]:
y = nn.Linear(3,2, bias=False)
print(type(y))
print(y.weight)
print(y.weight.shape)
input = torch.tensor([[1.2,2.,3.], [1.2,2.,3.]])
print(y(input))
print(torch.matmul(input, y.weight.T))

<class 'torch.nn.modules.linear.Linear'>
Parameter containing:
tensor([[ 0.5176, -0.0239, -0.5117],
        [ 0.1606, -0.1175, -0.5186]], requires_grad=True)
torch.Size([2, 3])
tensor([[-0.9617, -1.5981],
        [-0.9617, -1.5981]], grad_fn=<MmBackward0>)
tensor([[-0.9617, -1.5981],
        [-0.9617, -1.5981]], grad_fn=<MmBackward0>)


In [ ]:
m = nn.Dropout(p=0.5)
input = torch.randn(2, 16)
print(input)
output = m(input)
print(output)

tensor([[ 0.4130,  1.0925, -1.1565,  0.9010, -0.1884, -1.2726,  0.5765, -0.3559,
          0.7726,  0.6406,  1.7512,  0.1959,  1.7758, -0.1852,  1.0595,  1.2978],
        [-0.4828, -1.0801,  0.2704, -1.1818, -1.0340, -0.4947, -0.8951,  0.5340,
          0.9070,  0.0391,  0.6588, -0.2967,  0.2332, -1.3473, -0.8231, -0.5395]])
tensor([[ 0.8261,  0.0000, -2.3130,  0.0000, -0.3769, -2.5452,  0.0000, -0.7119,
          0.0000,  0.0000,  3.5023,  0.3918,  0.0000, -0.0000,  2.1190,  0.0000],
        [-0.0000, -2.1603,  0.0000, -2.3637, -0.0000, -0.9895, -0.0000,  1.0680,
          1.8140,  0.0783,  0.0000, -0.0000,  0.0000, -2.6946, -1.6462, -0.0000]])


In [ ]:
embeddings = nn.Embedding(10, 5)
print(embeddings)
print(embeddings.weight)

Embedding(10, 5)
Parameter containing:
tensor([[ 0.1194, -1.0332,  0.5838,  1.0166, -0.7942],
        [ 0.3674,  0.4293,  2.0289, -0.5153, -1.2263],
        [-0.1133,  0.3085, -0.4411, -0.7797, -0.7566],
        [ 1.5148, -0.2007,  0.6386, -0.4361, -1.0023],
        [ 0.3780,  0.0428,  0.5859, -1.3688, -1.4919],
        [ 0.2769,  1.0580, -0.0515,  0.1713, -0.2117],
        [-0.1788, -0.8498, -0.2729, -0.3485,  0.2413],
        [ 0.1828,  0.6247, -0.7940, -0.6748, -0.3877],
        [ 0.4497, -1.0259, -1.9105,  0.2609,  1.4178],
        [ 0.6738,  1.4666, -1.1077, -0.7444,  0.3588]], requires_grad=True)


In [ ]:
x = nn.Parameter(torch.ones(3))
print(type(x))
print(x.data)
print(x)

In [ ]:
mask = torch.triu(torch.ones(6, 6), diagonal=1)
print(mask)
print(mask.bool())

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[False,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]])


In [ ]:
attn_scores = torch.rand(6, 6)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[0.2983,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.4834, 0.3095,   -inf,   -inf,   -inf,   -inf],
        [0.8067, 0.0515, 0.0180,   -inf,   -inf,   -inf],
        [0.4034, 0.7282, 0.0612, 0.5736,   -inf,   -inf],
        [0.9970, 0.8077, 0.2231, 0.0903, 0.3789,   -inf],
        [0.6747, 0.5046, 0.9022, 0.6964, 0.4081, 0.5172]])


In [ ]:
a = torch.tensor([
    [
        [
        [0.2745, 0.6584, 0.2775, 0.8573],
        [0.8993, 0.0390, 0.9268, 0.7388],
        [0.7179, 0.7058, 0.9156, 0.4340]
        ],
        [
        [0.0772, 0.3565, 0.1479, 0.5331],
        [0.4066, 0.2318, 0.4545, 0.9737],
        [0.4606, 0.5159, 0.4220, 0.5786]
        ]
    ]
])

print(a.shape)
print(a.transpose(2, 3))

In [ ]:
b = a @ a.transpose(2, 3)
print(b.shape)
print(b)

In [ ]:
first_head = a[0, 0, : , :]
print(first_head)

In [ ]:
second_head = a[0, 1, : , :]
print(second_head)

In [ ]:
x = torch.randn(2, 6, 768)
print(x.shape)
y = x.view(2, 6, 12, 64)
print(y.shape)
context_vec = y.contiguous().view(2, 6, 768)
print(context_vec.shape)